In [176]:
import pandas as pd

df = pd.read_csv('HRDataset_v14.csv')

In [177]:
with pd.option_context('display.max_columns', None):
    print(df.head(5))

              Employee_Name  EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026          0                0         1
1  Ait Sidi, Karthikeyan     10084          1                1         1
2         Akinkuolie, Sarah  10196          1                1         0
3              Alagbe,Trina  10088          1                1         0
4          Anderson, Carol   10069          0                2         0

   EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  Salary  Termd  \
0            1       5            4                       0   62506      0
1            5       3            3                       0  104437      1
2            5       5            3                       0   64955      1
3            1       5            3                       0   64991      0
4            5       5            3                       0   50825      1

   PositionID                  Position State   Zip       DOB Sex MaritalDesc  \
0          19   Production Technician I    MA  1960  07/10/83  M       Single
1          27                   Sr. DBA    MA  2148  05/05/75  M      Married
2          20  Production Technician II    MA  1810  09/19/88   F     Married
3          19   Production Technician I    MA  1886  09/27/88   F     Married
4          19   Production Technician I    MA  2169  09/08/89   F    Divorced

  CitizenDesc HispanicLatino RaceDesc DateofHire DateofTermination  \
0  US Citizen             No    White   7/5/2011               NaN
1  US Citizen             No    White  3/30/2015         6/16/2016
2  US Citizen             No    White   7/5/2011         9/24/2012
3  US Citizen             No    White   1/7/2008               NaN
4  US Citizen             No    White  7/11/2011          9/6/2016

          TermReason        EmploymentStatus         Department  \
0  N/A-StillEmployed                  Active  Production
1      career change  Voluntarily Terminated              IT/IS
2              hours  Voluntarily Terminated  Production
3  N/A-StillEmployed                  Active  Production
4   return to school  Voluntarily Terminated  Production

      ManagerName  ManagerID RecruitmentSource PerformanceScore  \
0  Michael Albert       22.0          LinkedIn          Exceeds
1      Simon Roup        4.0            Indeed      Fully Meets
2  Kissy Sullivan       20.0          LinkedIn      Fully Meets
3    Elijiah Gray       16.0            Indeed      Fully Meets
4  Webster Butler       39.0     Google Search      Fully Meets

   EngagementSurvey  EmpSatisfaction  SpecialProjectsCount  \
0              4.60                5                     0
1              4.96                3                     6
2              3.02                3                     0
3              4.84                5                     0
4              5.00                4                     0

  LastPerformanceReview_Date  DaysLateLast30  Absences
0                  1/17/2019               0         1
1                  2/24/2016               0        17
2                  5/15/2012               0         3
3                   1/3/2019               0        15
4                   2/1/2016               0         2

In [179]:
print(df.shape)

(311, 36)

In [227]:
total_bytes = df.memory_usage(deep=True).sum()
print("total bytes:", total_bytes)

df.info(memory_usage='deep')

total bytes: 374014
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Employee_Name                311 non-null    object
 1   EmpID                        311 non-null    int64
 2   MarriedID                    311 non-null    int64
 3   MaritalStatusID              311 non-null    int64
 4   GenderID                     311 non-null    int64
 5   EmpStatusID                  311 non-null    int64
 6   DeptID                       311 non-null    int64
 7   PerfScoreID                  311 non-null    int64
 8   FromDiversityJobFairID       311 non-null    int64
 9   Salary                       311 non-null    int64
 10  Termd                        311 non-null    int64
 11  PositionID                   311 non-null    int64
 12  Position                     311 non-null    object
 13  State                        311 non-null    object
 14  Zip                          311 non-null    int64
 15  DOB                          311 non-null    datetime64[ns]
 16  Sex                          311 non-null    object
 17  MaritalDesc                  311 non-null    object
 18  CitizenDesc                  311 non-null    object
 19  HispanicLatino               311 non-null    object
 20  RaceDesc                     311 non-null    object
 21  DateofHire                   311 non-null    datetime64[ns]
 22  DateofTermination            311 non-null    datetime64[ns]
 23  TermReason                   311 non-null    object
 24  EmploymentStatus             311 non-null    object
 25  Department                   311 non-null    object
 26  ManagerName                  311 non-null    object
 27  ManagerID                    311 non-null    float64
 28  RecruitmentSource            311 non-null    object
 29  PerformanceScore             311 non-null    object
 30  Performance_Score_Converted  311 non-null    int64
 31  EngagementSurvey             311 non-null    float64
 32  EmpSatisfaction              311 non-null    int64
 33  SpecialProjectsCount         311 non-null    int64
 34  LastPerformanceReview_Date   311 non-null    datetime64[ns]
 35  DaysLateLast30               311 non-null    int64
 36  Absences                     311 non-null    int64
 37  Employee_Class               311 non-null    object
dtypes: datetime64[ns](4), float64(2), int64(17), object(15)
memory usage: 365.2 KB

In [183]:
#need to add employee class
df['Employee_Class'] = 'Employee (Permanent)'

In [185]:
df.head(2)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,Employee_Class
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1,Employee (Permanent)
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17,Employee (Permanent)

In [186]:
#change date format to yyyy-mm-dd
print(df.iloc[:, [15, 21, 22, 33]].head(5))

        DOB DateofHire DateofTermination LastPerformanceReview_Date
0  07/10/83   7/5/2011               NaN                  1/17/2019
1  05/05/75  3/30/2015         6/16/2016                  2/24/2016
2  09/19/88   7/5/2011         9/24/2012                  5/15/2012
3  09/27/88   1/7/2008               NaN                   1/3/2019
4  09/08/89  7/11/2011          9/6/2016                   2/1/2016

In [192]:
#change date format to yyyy-mm-dd
df.iloc[:, 33] = pd.to_datetime(df.iloc[:, 33])
df.iloc[:, 33] = df.iloc[:, 33].dt.strftime('%Y-%m-%d')

In [197]:
df.iloc[:, 33] = pd.to_datetime(df.iloc[:, 33])

In [207]:
print(df.iloc[:, [15, 21, 22, 33]].head(5))

         DOB DateofHire DateofTermination LastPerformanceReview_Date
0 1983-07-10 2011-07-05        2016-06-16                 2019-01-17
1 2075-05-05 2015-03-30        2016-06-16                 2016-02-24
2 1988-09-19 2011-07-05        2012-09-24                 2012-05-15
3 1988-09-27 2008-01-07        2016-09-06                 2019-01-03
4 1989-09-08 2011-07-11        2016-09-06                 2016-02-01

In [206]:
#backfilling the NaT values in Termn dates
df.iloc[:, 33] = df.iloc[:, 33].bfill()

In [215]:
print(df.isnull().sum().sum())

0

In [216]:
#percentage of null values
print(df.isnull().mean() * 100)

Employee_Name                 0.0
EmpID                         0.0
MarriedID                     0.0
MaritalStatusID               0.0
GenderID                      0.0
EmpStatusID                   0.0
DeptID                        0.0
PerfScoreID                   0.0
FromDiversityJobFairID        0.0
Salary                        0.0
Termd                         0.0
PositionID                    0.0
Position                      0.0
State                         0.0
Zip                           0.0
DOB                           0.0
Sex                           0.0
MaritalDesc                   0.0
CitizenDesc                   0.0
HispanicLatino                0.0
RaceDesc                      0.0
DateofHire                    0.0
DateofTermination             0.0
TermReason                    0.0
EmploymentStatus              0.0
Department                    0.0
ManagerName                   0.0
ManagerID                     0.0
RecruitmentSource             0.0
PerformanceScore              0.0
EngagementSurvey              0.0
EmpSatisfaction               0.0
SpecialProjectsCount          0.0
LastPerformanceReview_Date    0.0
DaysLateLast30                0.0
Absences                      0.0
Employee_Class                0.0
dtype: float64

In [217]:
null_rows = df[df['ManagerID'].isnull()]
with pd.option_context('display.max_columns', None):
    print(null_rows)

Empty DataFrame
Columns: [Employee_Name, EmpID, MarriedID, MaritalStatusID, GenderID, EmpStatusID, DeptID, PerfScoreID, FromDiversityJobFairID, Salary, Termd, PositionID, Position, State, Zip, DOB, Sex, MaritalDesc, CitizenDesc, HispanicLatino, RaceDesc, DateofHire, DateofTermination, TermReason, EmploymentStatus, Department, ManagerName, ManagerID, RecruitmentSource, PerformanceScore, EngagementSurvey, EmpSatisfaction, SpecialProjectsCount, LastPerformanceReview_Date, DaysLateLast30, Absences, Employee_Class]
Index: []

In [213]:
df['DateofTermination'] = df['DateofTermination'].fillna(pd.Timestamp('2010-08-30 00:00:00'))

In [214]:
df['ManagerID'] = df['ManagerID'].fillna(float('0.0'))

In [220]:
#seeing unique score values
distinct_values = df['PerformanceScore'].unique()
print(distinct_values)

['Exceeds' 'Fully Meets' 'Needs Improvement' 'PIP']

In [224]:
#df.insert(30, 'Performance_Score_Converted', '1')
df['Performance_Score_Converted'] = df['Performance_Score_Converted'].astype(float)

In [225]:
#mapping
mapping_dict = {'Exceeds': 4, 'Fully Meets': 3, 'Needs Improvement': 2, 'PIP' : 1}
df['Performance_Score_Converted'] = df['PerformanceScore'].replace(mapping_dict)

In [226]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,RecruitmentSource,PerformanceScore,Performance_Score_Converted,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,Employee_Class
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,LinkedIn,Exceeds,4,4.60,5,0,2019-01-17,0,1,Employee (Permanent)
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Indeed,Fully Meets,3,4.96,3,6,2016-02-24,0,17,Employee (Permanent)
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,LinkedIn,Fully Meets,3,3.02,3,0,2012-05-15,0,3,Employee (Permanent)
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Indeed,Fully Meets,3,4.84,5,0,2019-01-03,0,15,Employee (Permanent)
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Google Search,Fully Meets,3,5.00,4,0,2016-02-01,0,2,Employee (Permanent)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,"Woodson, Jason",10135,0,0,1,1,5,3,0,65893,...,LinkedIn,Fully Meets,3,4.07,4,0,2019-02-28,0,13,Employee (Permanent)
307,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Google Search,PIP,1,3.20,2,0,2015-09-02,5,4,Employee (Permanent)
308,"Zamora, Jennifer",10010,0,0,0,1,3,4,0,220450,...,Employee Referral,Exceeds,4,4.60,5,6,2019-02-21,0,16,Employee (Permanent)
309,"Zhou, Julia",10043,0,0,0,1,3,3,0,89292,...,Employee Referral,Fully Meets,3,5.00,3,5,2019-02-01,0,11,Employee (Permanent)
310,"Zima, Colleen",10271,0,4,0,1,5,3,0,45046,...,LinkedIn,Fully Meets,3,4.50,5,0,2019-01-30,0,2,Employee (Permanent)

In [263]:
distinct_values = df[df['DateofHire'] > '2017-01-01']
#with pd.option_context('display.max_rows', None):
print("Rows:", distinct_values.count().sum()/38)

Rows: 7.0

In [262]:
#change the employee class based on the date of hire 
df.loc[df['DateofHire'] > '2017-01-01', 'Employee_Class'] = 'Employee (Fixed Term)'

In [264]:
distinct_values

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,RecruitmentSource,PerformanceScore,Performance_Score_Converted,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,Employee_Class
64,"Dee, Randy",10311,1,1,1,1,6,1,0,56991,...,Indeed,Fully Meets,3,4.30,4,3,2019-01-31,2,2,Employee (Fixed Term)
70,"DeVito, Tommy",10197,0,0,1,1,3,3,0,96820,...,Indeed,Fully Meets,3,3.01,5,7,2019-01-23,0,15,Employee (Fixed Term)
120,"Gruber, Hans",10234,1,1,1,1,3,3,0,99020,...,Indeed,Fully Meets,3,4.20,5,5,2019-01-28,0,8,Employee (Fixed Term)
197,"Navathe, Kurt",10079,0,0,1,1,3,3,0,87921,...,Indeed,Fully Meets,3,5.00,3,6,2019-02-25,0,17,Employee (Fixed Term)
240,"Roper, Katie",10086,0,0,0,1,3,3,0,150290,...,Indeed,Fully Meets,3,4.94,3,5,2019-02-06,0,17,Employee (Fixed Term)
275,"Tannen, Biff",10173,1,1,1,1,3,3,0,90100,...,Indeed,Fully Meets,3,3.40,3,6,2019-01-02,0,14,Employee (Fixed Term)
298,"Wang, Charlie",10172,0,0,1,1,3,3,0,84903,...,Indeed,Fully Meets,3,3.42,4,7,2019-01-04,0,17,Employee (Fixed Term)

In [265]:
#export the df to csv
df.to_csv('HR_self.csv', index=False)